### ISSUE TITLE
Version that is compatible with .NetStandard 1.3

### ISSUE THREAD

**Issue by ravensorb** [StephenClearyArchive/AsyncLocal#1]
Is there a newer version that is compatible with .NetStandard profiles?

**Comment by StephenCleary** [comment]
I believe AsyncLocal is built-in to netstandard1.3

**Comment by ravensorb** [comment]
Hmm, ok I'll keep looking as I cannot seem to find it anywhere

**Comment by StephenCleary** [comment]
It's [in the `System.Threading` package](http://dotnetapis.com/pkg/System.Threading/4.0.11/netstandard1.3/doc/System.Threading.AsyncLocal'1).
